language: scala
jdk:
- openjdk8

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - name: compile
      script: sbt compile
    - name: formatting
      script: sbt scalafmtCheck scalafmtSbtCheck
    - stage: release
      env:
      - SCALAPB_VERSION: 0.9
      script: ./release.sh
    - stage: release
      env:
      - SCALAPB_VERSION: 0.10
      script: ./release.sh
