language: scala
jdk:
- openjdk8

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - name: compile and format
      script: sbt compile scalafmtCheck scalafmtSbtCheck
    - stage: release
      script: ./release.sh
