name: Release

on:
  push:
    branches: [master]
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Scala caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-docs-${{ hashFiles('**/*.sbt') }}
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: olafurpg/setup-gpg@v3
      if: startsWith(github.ref, 'refs/tags/v')
    - name: "Publish release: ${{github.ref}}"
      if: startsWith(github.ref, 'refs/tags/v')
      run: PUBLISH_ONLY=${GITHUB_REF%%/*} RELEASE=1 sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
    - name: "Publish snapshot: ${{github.ref}}"
      if: "!startsWith(github.ref, 'refs/tags/v')"
      run: sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
